[tox]
envlist = qa,py311,py312,py313,py314,py315,pypy311
skipsdist = true

[testenv]
deps =
	lxml
	pytest
commands =
	pytest -vv

[testenv:qa]
skip_install = True
deps =
	ruff
commands =
	ruff check {posargs:eselect-repo-helper test}

